### ISSUE TITLE
去掉【收藏】有关的功能

### ISSUE THREAD

**Issue by alsotang** [TakWolf/CNode-Material-Design#1]
之后我们社区不打算提供的收藏功能，麻烦应用检查一下是否有接触到相关的功能，如果有的话，可以全部去掉。

**Comment by TakWolf** [comment]
收到，正在处理中

**Comment by liygheart** [comment]
@alsotang 收藏功能现在不是还有吗？为啥以后不提供了呢？看到一个很好的话题想收藏但没这功能岂不是很难受？

**Comment by TakWolf** [comment]
@liygheart 这个是很早的issues了

社区最早是有的收藏功能的

后来为了精简功能，给去掉了

大约1个月前由于大家呼声高，又弄回来了

------------- 分割线 ---------------

这个实例充分的教育了我们，程序员们是一群 【生命不息，折腾不止】的人。

**Comment by liygheart** [comment]
再精简也不能去掉收藏功能呀@alsotang 你当出怎么想做的呀！

**Comment by XGHeaven** [comment]
@liygheart 那也不一定啊，就像是收藏的东西你能点进去几次呀。。跟 flarum 相比，我觉得关注比收藏更好。至少收藏缺少一种交互，楼主更改后，没有通知，没有消息。但是关注就不一样了。

**Comment by TakWolf** [comment]
我自己收藏用的是 chrome bookmarks
每个人有自己的习惯，去掉也不是没道理
现在加回来也是合理的

**Comment by XGHeaven** [comment]
其实如果不加回来的话，我都要写一个跟微博似的 @我的印象笔记 了 😂

**Comment by liygheart** [comment]
@TakWolf 确实属于个人习惯 
@XGHeaven 我每天在公交上会看看新闻，资讯之类的信息，基本上都是大致浏览一下，觉得不错的，习惯点一下收藏
有时候正巧刚打开一个自己感兴趣的内容，结果车到站了，就赶紧点一个 收藏，到公司或者回家在接着看，因为有些app，重新打开后会重启
所以我还是很依赖收藏这个功能的

**Comment by XGHeaven** [comment]
哦，这样。确实是，这个东西很依赖个人的习惯。我以前也是喜欢收藏一下，后来发现收藏之后根本不会再去看。然后我就懒得收藏了。我只是觉得既然这个功能已经回来了，就没必要去追究当初去掉的原因了
:joy:

朋也 <notifications@github.com>于2016年4月20日周三 下午11:16写道：

**Comment by alsotang** [comment]
因为我觉得在 web
上来说的话，很多的第三方chrome插件可以把收藏这件事做得更专业，所以社区就不想自己提供了。我个人是使用印象笔记的插件来收藏网页的。


在 2016年4月20日 下午11:22，Xu Tianyang <notifications@github.com>写道：
