### ISSUE TITLE
Error:Project 'markdown-view' not found in root project 'CNode-Material-Design'.

### ISSUE THREAD

**Issue by tianshaokai** [TakWolf/CNode-Material-Design#10]
这个项目在哪加载了呢，怎么又报这个错误

**Comment by TakWolf** [comment]
将代码同步到 master 的最新提交，之后在rebuild

markdown-view 这个依赖已在最新版中移除了

**Comment by oero** [comment]
@TakWolf  clone后怎么导入project

**Comment by TakWolf** [comment]
@oero 

保证IDE是Android Studio，不要用eclipse。项目结构不支持eclipse，转换也很麻烦。

欢迎页选择 
![image](https://cloud.githubusercontent.com/assets/6064962/11872678/9c09ff62-a511-11e5-971e-415f906abc8b.png)

或者菜单键
File -> New -> Import project

选择项目根目录，等待gradle构建完成

**Comment by oero** [comment]
@TakWolf  是as啊 
can not import anything from /home/cnodexxx.zip

**Comment by TakWolf** [comment]
@oero 
需要解压

**Comment by oero** [comment]
@TakWolf  怪不得,刚才解压后,正在Gradle project
应该可以了吧

**Comment by TakWolf** [comment]
@oero 
可以了。构建结束之后可能会报这个错误，参考这个issues


https://github.com/TakWolf/CNode-Material-Design/issues/9

**Comment by oero** [comment]
@TakWolf  非常感谢!

**Comment by TakWolf** [comment]
@tianshaokai 
问题解决了吗？
