### ISSUE TITLE
compile ('com.afollestad.material-dialogs:core:0.8.5.0@aar') { transitive = true } 

### ISSUE THREAD

**Issue by hustsqh** [TakWolf/CNode-Material-Design#11]
使用android studio 1.4编译出现如下错误：

Error:(69, 14) Failed to resolve: com.afollestad.material-dialogs:core:0.8.5.0
<a href="openFile:D:/Users/shiqianhua/Documents/android_test/others/CNode-Material-Design-develop/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

这个是什么原因？

换成官方推荐的配置：compile('com.github.afollestad.material-dialogs:core:0.8.5.4@aar') { transitive = true }

还是一样的错误，这是什么原因？

在stackoverflow找到类型的问题，根据提示导入证书，也没解决，

http://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse

卡在这里来，帮帮忙解答一下， 谢谢！！

**Comment by TakWolf** [comment]
Android Studio 1.5.1 没出现问题
感觉貌似和证书没关系

Material Dialogs 这个托管在 https://jitpack.io 上，先确保https://jitpack.io的maven仓库是可以访问的
