### ISSUE TITLE
夜间模式问题

### ISSUE THREAD

**Issue by Henryzhugithub** [TakWolf/CNode-Material-Design#12]
进入设置切换夜间模式后，back到主活动，然后一直back键无法退出程序

**Comment by TakWolf** [comment]
系统版本和手机型号是什么

**Comment by Henryzhugithub** [comment]
其他手机（金立）我也试过了，也是这种情况

**Comment by TakWolf** [comment]
研究了很多方案，基于多主题 recreate 方式实现主题切换，目前无法解决闪烁问题。
当前项目中还是用了兼容方案 handler.post 的方式解决Activity resume的问题

**Comment by TakWolf** [comment]
https://github.com/TakWolf/CNode-Material-Design/issues/15
