### ISSUE TITLE
为啥不能收藏话题呀？

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#13]
rt

**Comment by TakWolf** [comment]
还没搞呢，过几天补上

**Comment by TakWolf** [comment]
其实根本原因是因为懒

**Comment by liygheart** [comment]
好吧，期待。。。

**Comment by TakWolf** [comment]
https://github.com/TakWolf/CNode-Material-Design/releases/tag/1.1.0

已更新，收藏话题功能已添加
版本是 v1.1.0-build-20160418

请在FIR上下载 [http://fir.im/CNodeMD](http://fir.im/CNodeMD) ，或者等待各大应用商店更新上架
