### ISSUE TITLE
评论主题的时候，可以指定回复某一个楼层

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/CNode-Material-Design#14]
这个需求还包括，评论列表显示的时候也要显示这个数据

**Comment by XGHeaven** [comment]
现在不是么。。。

**Comment by TakWolf** [comment]
@XGHeaven  

`reply_id String 如果这个评论是对另一个评论的回复，请务必带上此字段。这样前端就可以构建出评论线索图。`

现在不是，提交数据的时候，没用加这个id

**Comment by XGHeaven** [comment]
哦，这样

**Comment by TakWolf** [comment]
finish by https://github.com/TakWolf/CNode-Material-Design/commit/a6fce6d791228ea094ec4cb16126bd4d88f88c2a

**Comment by lazyman54** [comment]
#60 是这样子回复么

**Comment by lazyman54** [comment]
reply_id 12 这样子？

**Comment by touxing** [comment]
Duplicate of # 这样么，测试一下

**Comment by touxing** [comment]
reply_id String  测试

**Comment by touxing** [comment]
@TakWolf

**Comment by touxing** [comment]
reply_id String 这样？

**Comment by ShourenLan** [comment]
> Duplicate of # 这样么，测试一下

Test

**Comment by TouchDeeper** [comment]
reply_ 2 测试

**Comment by nieshiming** [comment]
> 这个需求还包括，评论列表显示的时候也要显示这个数据

1111

**Comment by nieshiming** [comment]
> > 这个需求还包括，评论列表显示的时候也要显示这个数据
> 
> 1111

222

**Comment by nieshiming** [comment]
> 哦，这样

111

**Comment by kekehaoz** [comment]
@TakWolf replay

**Comment by kekehaoz** [comment]
> @XGHeaven
> 
> `reply_id String 如果这个评论是对另一个评论的回复，请务必带上此字段。这样前端就可以构建出评论线索图。`
> 
> 现在不是，提交数据的时候，没用加这个id

@TakWolf 测试
