### ISSUE TITLE
关于Access Token 怎么获取

### ISSUE THREAD

**Issue by baoyachi** [TakWolf/CNode-Material-Design#16]
你好，请问如何获取该客户端的access token？

**Comment by TakWolf** [comment]
登录之后，进入设置页面 https://cnodejs.org/setting

滑到最底部，就要个人的accessToken。
可以直接扫描二维码。

**Comment by baoyachi** [comment]
谢谢，我已经登陆成功了

**Comment by alsotang** [comment]
这块在客户端还是缺少提示吗。。。这个提示可以让用户每次进入登录页面都看一遍啊。。。反正一般也就登录一次就不会再看到了。

2016-04-18 14:38 GMT+08:00 包牙齿 <notifications@github.com>:

**Comment by TakWolf** [comment]
@alsotang 是的，应该加个提示如果获取accessToken

**Comment by TakWolf** [comment]
fix by https://github.com/TakWolf/CNode-Material-Design/commit/e7beb82df52374f09f9413638d5f6b2368172940
