### ISSUE TITLE
在详情页点击图片查看的时候内容会返回顶部

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#17]

**Comment by TakWolf** [comment]
这是WebView的已知BUG，不仅是图片，任何连接都可能造成回弹。

原因是在recycle item体系中，外部高度计算和webview底部计算不一致导致的，点击的时候，可能会导致布局重新渲染，从而引发position位置变化。


这个问题目前暂未比较好的结局办法。

**Comment by TakWolf** [comment]
fix by https://github.com/TakWolf/CNode-Material-Design/commit/a42703b39412073662dcdaf1711d8c9db5e5745f

**Comment by TakWolf** [comment]
尝试修复了这个问题，请在FIR上更新版本到 1.1.1-beta.1 (Build 20160420) 

http://fir.im/CNodeMD

**Comment by liygheart** [comment]
已经好了，修复好及时，赞大大
