### ISSUE TITLE
可以不可以考虑将头像进行代理？

### ISSUE THREAD

**Issue by XGHeaven** [TakWolf/CNode-Material-Design#18]
用手机端的时候，网速你知道的。尤其是还要 github 去访问头像数据。根本显示不出来。

**Comment by TakWolf** [comment]
怎么代理？技术上怎么实现？

**Comment by TakWolf** [comment]
之前的论坛的头像是有代理接口的，后来备了案之后就给去掉了。不清楚是啥原理。

我觉得这个问题还好吧，即便是头像显示不出来，也没啥大问题。

**Comment by XGHeaven** [comment]
就是代理访问喽，我这里写了一个很简单的代理。比如说唐少的头像。
https://avatars.githubusercontent.com/u/1147375?v=3&s=120
代理之后的地址，就是把源图片地址 urlencode 一下，加在代理地址后面
http://simple-proxy.xgheaven.cn/https%3A%2F%2Favatars.githubusercontent.com%2Fu%2F1147375%3Fv%3D3%26s%3D120
虽然说比较慢，但是还能打开的。总比打不开好。

可以加一个选项，选择是否使用头像代理。。纯属强迫症。。

**Comment by TakWolf** [comment]
考虑了一下，还是决定不添加这个功能，原因是：

1.头像加载失败不是一个严重的问题，并且客户端图片是有缓存策略的，这里可以调整
2.非nodeclub官方接口，希望项目可以和nodeclub分支匹配，因此尽量避免使用第三方接口。之前还考虑加入客户端上传图片的功能，自己搞了个第三方接口，后来考虑再三，还是没加。
3.没有显著的解决问题，加载还是很慢


以下这个功能是可以考虑的：
添加一个设置，关闭客户端加载图片以节省流量，开启后头像显示为md_avatar风格

![image](https://cloud.githubusercontent.com/assets/6064962/14679780/e017f648-074d-11e6-964f-b49660f9f95e.png)

https://github.com/lincanbin/Material-Design-Avatars/blob/master/README.md

**Comment by XGHeaven** [comment]
good，可以根据当前网络选择是否加载图片。如果能在不加载图片的时候可以点击加载图片，然后再次点击查看图片，这就更好了
TakWolf <notifications@github.com>于2016年4月20日周三 下午11:16写道：

**Comment by alsotang** [comment]
@takwolf
不是在备案以后取消了那个接口。。。是因为之前服务器在国外，所以具备代理的能力，现在服务器在国内，跟普通用户的网络一样，其实就没什么好代理的了。

之前之所以我这边会帮头像弄个代理需求，是因为有段时间gfw打炮打了一次github，后来又封了一点它的网址，其中就包括头像的domain，所以才开的代理。

在 2016年4月20日 下午11:19，Xu Tianyang <notifications@github.com>写道：
