### ISSUE TITLE
At功能在回复的时候没用，当字符串处理了

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#19]
Rt

**Comment by TakWolf** [comment]
创建一个评论是在本地渲染的markdown，然后模拟创建一个对象插入List，这里暂时没实现@协议

**Comment by liygheart** [comment]
At功能应该在服务端做对吧！nodeclub没处理这块吗？

**Comment by TakWolf** [comment]
@liygheart 

服务端有md渲染功能，可以解析@协议
客户端也有md渲染功能，暂时没实现@协议

通常内容数据，都是开启mdrander参数有服务器渲染的，@都是正常解析的

客户端在本地使用md渲染的情况为：
1.在md编辑器编辑内容，然后点了预览
2.发表评论的这个动作成功后，客户端没有重新获取数据，而是在本地创建了一个数据，插到了List中

目前只有这两种情况，@不会解析
你提的这种情况属于第二种，你重新刷新一下页面，@就正常解析了

**Comment by liygheart** [comment]
你这样一说我就明白了，谢谢！

**Comment by TakWolf** [comment]
这个功能是应该添加的，就是懒得没搞。先放在这里有空弄。

**Comment by TakWolf** [comment]
fix by https://github.com/TakWolf/CNode-Material-Design/commit/a97bb9555ede0facae5587c05329041d78b2e4cb

**Comment by TakWolf** [comment]
该问题已修复，在FIR上更新版本到1.1.1-beta.2 (Build 20160421) 来测试

http://fir.im/CNodeMD?release_id=5717c619f2fc425e36000004

**Comment by liygheart** [comment]
好快，感谢大大

**Comment by alsotang** [comment]
所以现在的意思是，本地回复之后，虽然没有渲染 @ 对应的跳转链接，但实际上服务器是 at 成功的，对吧？

2016-04-21 10:02 GMT+08:00 朋也 <notifications@github.com>:

**Comment by TakWolf** [comment]
@alsotang 对的，服务器是正常渲染的，只是我本地渲染的时候没处理@

**Comment by alsotang** [comment]
哈哈，服务器处理这个 at 符号，也是正则表达式做的。

为了确定这个正则的正确，还写了一大串测试：
https://github.com/cnodejs/nodeclub/blob/master/test%2Fcommon%2Fat.test.js

2016-04-21 12:19 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by liygheart** [comment]
怎么有reopen了？

**Comment by TakWolf** [comment]
这里的匹配存在问题：

1. 邮件不应该被匹配，如 `takwolf@foxmail.com`不应该被匹配

2. 已经生成的@不应该匹配如 `[@TakWolf](/user/TakWolf)` ，实际上以` [`开头或者以`]`结尾的不匹配，但是这样的情况 `[ @TakWolf ](/user/TakWolf)`，不确定是不是正确的书写

3. 在代码块中和引用中的@不应该匹配

4. 连接的@应该被匹配例如：`@TakWolf@alsotong` 应该解析出两个连接

nodeclub的正则解析参考：

https://github.com/cnodejs/nodeclub/blob/master/common/at.js

**Comment by alsotang** [comment]
这个 at 功能已经很久没有改动了，我觉得你可以直接拿去用。

在 2016年5月27日 下午6:28，TakWolf <notifications@github.com>写道：

**Comment by TakWolf** [comment]
finish by https://github.com/TakWolf/CNode-Material-Design/commit/b0dd4c85087dc8d003ef525c2f1bfc2df9fa1d6d
