### ISSUE TITLE
user.avatar_url 返回值更新

### ISSUE THREAD

**Issue by alsotang** [TakWolf/CNode-Material-Design#2]
这个 avatar_url 有更新，之前返回的是 `/agent?url=xxxx` 的地址，现在服务器准备回到国内，所以不再具备代理能力。之后这里会直接返回 `url=xxxx` 的真实url

**Comment by alsotang** [comment]
新 avatar_url 示例：https://cnodejs.org/api/v1/user/alsotang

**Comment by TakWolf** [comment]
已修复
