### ISSUE TITLE
图片加载策略优化

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/CNode-Material-Design#20]
问题来源于 https://github.com/TakWolf/CNode-Material-Design/issues/18

图片加载包括用户头像和正文图片两个部分
具体策略待定

**Comment by TakWolf** [comment]
webview中无法实现图片代理加载（也可以实现，但是工作量巨大，相当于不使用<img>而完全手动解析图片），并且现有的图片加载策略也并无大问题，因此放弃实现这个特性。

**Comment by alsotang** [comment]
是的，不用做懒加载啦。

2016-05-09 10:13 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by alsotang** [comment]
噢噢，代理啊，代理就算了。github 的头像也没那么慢。
