### ISSUE TITLE
希望能增加一个分享功能

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#21]
在客户端看到某个话题想分享给别人，要先点击右上角在浏览器中打开，然后借助浏览器才能分享，有点麻烦，希望能增加在app内部分享的功能

**Comment by TakWolf** [comment]
分享只打算支持Andriod原生的分享，不会引入第三方分享组件

**Comment by liygheart** [comment]
赞个，喜欢原生的东西😀
2016年4月25日 22:43，"TakWolf" <notifications@github.com>写道：

**Comment by TakWolf** [comment]
fix by https://github.com/TakWolf/CNode-Material-Design/commit/52fb9acbce1a4107e7bc4874811fc75fe8fc0565

**Comment by liygheart** [comment]
还没打包吧

**Comment by liygheart** [comment]
今天更新跟编辑器的粘贴bug一块修复了，赞
