### ISSUE TITLE
编辑器长按不出现粘贴

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#22]
在别处复制的内容，没法粘贴，希望大大看一下

**Comment by TakWolf** [comment]
帖子回复的编辑器无法粘贴，创建帖子是正常的对吗？

**Comment by liygheart** [comment]
是的

**Comment by TakWolf** [comment]
记录：编辑框使用 popupwindow 实现，无法出现粘贴面板，这是android的一个bug
相关讨论：
http://stackoverflow.com/questions/15857755/android-textview-does-not-support-text-selection-action-mode-cancelled

**Comment by TakWolf** [comment]
新建话题页面的输入框也有滚动问题

**Comment by TakWolf** [comment]
fix by https://github.com/TakWolf/CNode-Material-Design/commit/e06cf7b88359d401b7767df6a03d8a381faf1b9a

**Comment by TakWolf** [comment]
已打包，去FIR上更新 1.1.1-beta.3 (Build 20160501) 
http://fir.im/CNodeMD

**Comment by liygheart** [comment]
已更新，感谢大大迅速修复！！
