### ISSUE TITLE
适配Android 6.0权限系统

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/CNode-Material-Design#23]
二维码扫描需要相机权限

google play政策紧缩，消极兼容方式已经无法通过审核了

**Comment by TakWolf** [comment]
finish by https://github.com/TakWolf/CNode-Material-Design/commit/ca2eaddad4328ebe47e05745853830e48d6c40b5

**Comment by alsotang** [comment]
动作好快啊

2016-05-03 7:18 GMT+08:00 TakWolf <notifications@github.com>:
