### ISSUE TITLE
bug 评论列表刷新会乱跳

### ISSUE THREAD

**Issue by gincoo** [TakWolf/CNode-Material-Design#25]
评论列表刷新会乱跳

**Comment by TakWolf** [comment]
markdown渲染使用的是webview，目前没有找到其他更好的markdown渲染方式

话题详情页面，ListView每一个item都是一个webview，ListView滚动造成item回收，webview都会不断重载内容，会造成item不断拉长。
这么做确实会有严重的效率问题。消息页面实现原理相同，因此有相同的问题。

但是目前该问题没有其他更好的解决方案，暂时也不打算修复。
有一种方案是整个页面渲染成webview，这么做可以解决上述问题，但是会引入过多web内容，因此不打算采用该方案（该项目希望整体上可以基于原生实现，如果希望通过整页面渲染成web，可以参考其他整体基于web技术实现的客户端）。

webview还有其他一些bug存在，这些问题主要存在android 4.x上。在android 5.x之后表现还算基本可以接受。

更详细的讨论，请参考 https://github.com/TakWolf/CNode-Material-Design/issues/8

**Comment by TakWolf** [comment]
问题迁移到 https://github.com/TakWolf/CNode-Material-Design/issues/26
