### ISSUE TITLE
Markdown渲染策略调整

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/CNode-Material-Design#26]
问题来源：
https://github.com/TakWolf/CNode-Material-Design/issues/7
https://github.com/TakWolf/CNode-Material-Design/issues/8
https://github.com/TakWolf/CNode-Material-Design/issues/25
https://github.com/TakWolf/CNode-Material-Design/issues/31

**Comment by TakWolf** [comment]
目前客户端markdown渲染使用webview来实现，存在以下问题：

1.ListView中每个item都是webview，滚动回收造成item重用使webview不断重复加载，造成页面跳动 https://github.com/TakWolf/CNode-Material-Design/issues/25
2.跟1相同的原因，在部分手机上，被拉长的webview无法缩短 https://github.com/TakWolf/CNode-Material-Design/issues/8
3.不太版本手机样式存在细微差别 https://github.com/TakWolf/CNode-Material-Design/issues/7

以上问题，目前没有有效的解决手段

**Comment by TakWolf** [comment]
一种可选方案：使用原生TextView通过SpannableString实现富文本渲染，存在以下问题：

1.网络图片加载存在问题，试了几种方法都无法解决该问题
2.无法支持复杂css样式，主要影响到图片和代码个显示样式
3.实现代码复杂，扩展难度非常大

**Comment by TakWolf** [comment]
一种可选方案：仍然使用webview，但是把ListView替换为scrollview

这样相当于初始化的时候，一次性实例化所以内容，全部放到页面中，并且不适用重用
该方案可以有效解决由于item回收造成的webview的诸多问题，但是会有更严重的内存占用问题，非常容易产生oom

**Comment by TakWolf** [comment]
一种可选方案：原来的ListView页面，改为使用两个webview来实现渲染，分别是header和replylist

该方案可以有效解决由于item回收造成的webview的诸多问题
问题是引入了较多web解决方案，包括非常多ui部分，这里可能会跟其他原生部分的显示样式造成差异；web跟原生代码的通信机制也比较复杂

**Comment by TakWolf** [comment]
一种可选方案：话题详情页面item不支持富文本

这样没有了webview也就没有了诸多问题，但是会造成功能缺失。

**Comment by TakWolf** [comment]
一种可选方案：自己扩展view从底层重新实现渲染，或者通过源码自己引入webview替代系统内置

简直作死！！！

**Comment by XGHeaven** [comment]
提一个想法。就是类似知乎。分两部分。对于评论，可以显示一个纯文字的概要，然后点击进去查看详细。对于文章主体，我建议将md的格式进行分析，分析出里面的图片，标题，加粗什么的。然后分别用原生方式实现。很喜欢md设计里面标题悬浮的感觉

TakWolf <notifications@github.com>于2016年5月1日周日 16:36写道：

**Comment by TakWolf** [comment]
尝试解决这个问题，方案在：https://github.com/TakWolf/CNodeMD-Page-Render-Compat

**Comment by TakWolf** [comment]
finish by https://github.com/TakWolf/CNode-Material-Design/commit/05664b818df6ae0b96cf82fbdf4cd274f33bdf40

**Comment by TakWolf** [comment]
该问题已经通过 https://github.com/TakWolf/CNode-Material-Design/issues/34 解决
