### ISSUE TITLE
希望能把收藏的心图标放在分享旁边

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#28]
有时候看内容不知不觉就翻到下面去了，想收藏还要往上翻，感觉不太方便

**Comment by alsotang** [comment]
敲一下屏幕的顶部就可以回到最上吗

**Comment by TakWolf** [comment]
之前考虑过这个问题，没放到app bar上是觉得样式有点问题。
我把各种图弄出来你感受一下：

![1](https://cloud.githubusercontent.com/assets/6064962/15043389/38a6c106-12ff-11e6-8906-3cc0261bea31.png)

![2](https://cloud.githubusercontent.com/assets/6064962/15043393/3fc5aec0-12ff-11e6-9f74-e48cccedabd6.png)

![3](https://cloud.githubusercontent.com/assets/6064962/15043395/4244b5b0-12ff-11e6-9413-4960a7532ae7.png)

我现在更倾向于双击appbar返回顶部来解决这个问题。

**Comment by liygheart** [comment]
我手机nexus5x双击没反应

如果把收藏后的实心颜色改成白色我感觉还可以

TakWolf <notifications@github.com>于2016年5月5日周四 20:23写道：

**Comment by TakWolf** [comment]
@liygheart  双击我还没做呢

白色感觉表意不明确，感觉双击返回顶部可以解决问题。我先把双击返回做出来你感受一下。

另外确定一下，你的nexus5x跑的系统版本是多少？

**Comment by TakWolf** [comment]
https://github.com/TakWolf/CNode-Material-Design/issues/29

**Comment by liygheart** [comment]
nexus5x是android6.0.1系统

**Comment by TakWolf** [comment]
appbar双击返回顶部已更新，在FIR下载。

看看能不能解决这个问题

**Comment by TakWolf** [comment]
这里现有设计暂时不改动
