### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by hedge-hog** [TakWolf/CNode-Material-Design#3]
学习的时候，也用到了这个项目

> compile 'com.afollestad:material-dialogs:0.7.6.0'

可是从在用的时候，Dialog弹出是黑色的，看了看，代码是一样的，可是CNode却是白色的。
想请问一下，在哪里设置Dialog的弹出颜色

**Comment by alsotang** [comment]
这个难道不是一搜就能搜到的配置？



在 2015年9月11日 下午1:46，JerryChen <notifications@github.com>写道：

**Comment by TakWolf** [comment]
material dialogs 默认使用你的主题颜色

![image](https://cloud.githubusercontent.com/assets/6064962/9808693/1ebc47dc-5894-11e5-9ff5-5151c52e4b08.png)

我使用的全局Style是 Theme.AppCompat.Light.NoActionBar，这个背景是白色的，因此dialog背景也是白色的

如果你的主题色不是Light，你也可以通过调用 MaterialDialog.backgroundColor() 手动配置

**Comment by hedge-hog** [comment]
首先，全局主题一直是
```
 <style name="BaseAppTheme" parent="Theme.AppCompat.Light.NoActionBar">
```
不曾变过

在使用

> 'com.afollestad:material-dialogs:0.6.XX

（该版本已经从Jcenter删除掉了）的时候，一直正常

更新到

> 'com.afollestad:material-dialogs:0.7.XX

之后，Dialog的背景就开始变成黑色

**已Google搜索过，没找到囧囧囧...**我的搜索姿势不对吧

通过调用 
> MaterialDialog.backgroundColor();

这个属性是可以设置的

不过我还是想知道为什么我的属性设置成Light为何Dialog还是黑色的

所以就建了一条Issues，并非纯伸手党

谢谢二位解答！

**Comment by TakWolf** [comment]
检查一下你的Activity是不是配置了单独的主题属性

**Comment by hedge-hog** [comment]
OK，我在找找问题，再次感谢！
