### ISSUE TITLE
希望能增加检测停止滚动就显示回复按钮

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#30]
在查看详情的时候，往下翻看回复，右下角的回复按钮会隐藏，而且停止滚动页面也不会出现

所以在看完内容和翻到底部的时候想回复还得往上翻一下，才能出来回复按钮，体验不是很好

个人意见：希望能增加 监听一下页面的滚动事件，当停止滚动后，大约2-3秒，就将回复按钮显示，可以随时回复

**Comment by TakWolf** [comment]
这个行为目前就是这么设计的。
隐藏floating Action Button是为了防止内容被遮挡。因此向下滑动隐藏，防止遮挡内容，向上滑动才出现。

**Comment by TakWolf** [comment]
一个可能的解决方案是：
我在评论最后一个item底部增加空白空间，高度大于fab的高度。
增加一个行为是，list滑动到最低部的时候，弹出fab，其他行为跟之前一样不变

**Comment by liygheart** [comment]
如果看内容还没看评论就回复，这时候还没翻到底部，还是要往上翻一下，设计是这样就不要改了

TakWolf <notifications@github.com>于2016年5月5日周四 22:45写道：

**Comment by TakWolf** [comment]
这个issues先保留着

**Comment by alsotang** [comment]
我大概看明白朋也的意思了。

知乎的回答详情页目前跟 @tak 的实现是一样的，当滚动停止的时候，底部bar也不会弹出，要上拉一下才会。

在我看来，大部分时候我们是阅读而不是需要回复，滚动停下很可能只是在专心在其中的一段代码，所以低频需求让位高频需求，这个地方我赞成不改动。

2016-05-05 22:59 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by TakWolf** [comment]
考虑了一下还是决定不改动，保持现有的行为。

这个问题确实存在，但是目前其他第三方在fab的交互方案也是同样的，没有找到更优雅的交互案例，暂时就不改动。
