### ISSUE TITLE
详情页下的评论列表体验好不舒服

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#31]
没看源码，猜测是一个评论是一个webview

我现在用的感觉是当一个评论比较长的话，如果往上翻的话会突然页面下来一大截，如果往下翻，碰到下面有一个比较长的评论会突然一下子往上串一大截，不知道大大碰到没

**Comment by TakWolf** [comment]
这是一个已知问题，详细的参考这里：
https://github.com/TakWolf/CNode-Material-Design/issues/26

**Comment by liygheart** [comment]
不好意思，没在意看
