### ISSUE TITLE
关于推送

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#32]
刚想去nodeclub去提一下推送的功能结果在issues里翻到了这个https://github.com/cnodejs/nodeclub/issues/667

不知道nodeclub现在支持了没，如果支持了，希望大大能把推送功能完善😄

**Comment by TakWolf** [comment]
推送已经被 @alsotang 干掉了，详情参考：https://github.com/lanceli/cnodejs-ionic/issues/41

客户端设置页面的控件会保留，方便其他人做二次开发的时候直接实现

**Comment by liygheart** [comment]
多好的功能 @alsotang ……

**Comment by alsotang** [comment]
推送先不支持了。我觉得没推送挺好的，推送给人压力。。

2016-05-06 0:02 GMT+08:00 朋也 <notifications@github.com>:
