### ISSUE TITLE
启用客户端渲染Markdown的时候，存在xss风险

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/CNode-Material-Design#33]
问题来源：https://github.com/cnodejs/nodeclub/issues/844

目前线上版本Markdown使用服务端渲染，但是编译时可以配置为使用客户端渲染。客户端渲染的过程中没有过滤xss，这里需要完善。

客户端使用webview作为markdown容器，因为需要支持其他特性，所以开启了javascript以及本地代码交互。较低版本的webview（API < 17）在启用javascript的时候，存在反射漏洞，即通过反射调用未公开的本地方法。所以，理论上，通过在Markdown注入xss，并通过webview反射漏洞获取手机权限，理论上是可行的。

**Comment by alsotang** [comment]
android 没有 xss 过滤库吗？

在 2016年5月11日 上午6:44，TakWolf <notifications@github.com>写道：

**Comment by TakWolf** [comment]
尝试使用jsoup处理：

https://jsoup.org/cookbook/cleaning-html/whitelist-sanitizer

**Comment by liygheart** [comment]
想问下，如果markdown解析器设置html不解析，这样还会遭到xss的攻击吗？
也就是输入<script>alert(1)</script>
markdown解析完成后，输出到页面上还是<script>alert(1)</script>，而不是弹一个窗
我测试这样是可以避免的，所以一直不明白markdown里xss还有那些手段攻击（我举例的那个是最简单的了，不要吐槽这个啦~）

**Comment by alsotang** [comment]
设置 html 不解析的话，应该能很大程度避免 xss 攻击吧。

在链接的 herf 里面是可以写 javascript 的，这个不懂 markdown 自身会不会过滤掉

在 2016年5月22日 下午10:13，朋也 <notifications@github.com>写道：

**Comment by TakWolf** [comment]
finish by https://github.com/TakWolf/CNode-Material-Design/commit/07add21edf7532b9cc9df84d6eeb6e5285b500ca
