### ISSUE TITLE
本地Markdown转换如果Image的alt为空则不转换，例如格式：![](https://some.url)

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/CNode-Material-Design#35]
`![](https://some.url)`

alt属性为空，转换失败

这个是第三方库的BUG，问题跟踪地址：https://github.com/lruiz/MarkdownPapers/issues/50

**Comment by liygheart** [comment]
我表示从来没写过alt，都是置为空

**Comment by TakWolf** [comment]
第三方库作者已死。

暴力修复，fix by https://github.com/TakWolf/CNode-Material-Design/commit/5ee8619a20d0f928a8fb799f4960c23b2238df06

**Comment by alsotang** [comment]
哈哈哈

2016-05-16 20:02 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by TakWolf** [comment]
官方修复了这个问题，等待新版本部署

**Comment by TakWolf** [comment]
fix by https://github.com/TakWolf/CNode-Material-Design/commit/3c9fc4be13a9bbd5d2080be98589538d4f3fe4cc
