### ISSUE TITLE
话题详情代码块左滑会伴随上下滚动，体验不是很好！！

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#38]

**Comment by TakWolf** [comment]
什么意思

**Comment by liygheart** [comment]
就是代码块下会有一个滚动条，可以查看右边隐藏的代码
当我往左滑的时候，体验不是很好

**Comment by TakWolf** [comment]
体验不好的原因是什么？
左滑的时候会上下滚动？具体是怎么滚的？

markdown使用的css是这个
https://github.com/sindresorhus/github-markdown-css

**Comment by liygheart** [comment]
![image](https://cloud.githubusercontent.com/assets/6915570/15400769/43f0a3bc-1e1f-11e6-93ff-d569d7302b0b.png)

就是这个意思，你在app里感受下

**Comment by TakWolf** [comment]
没出现上下滚动的情况。

体验不好是指需要左滑吗？
代码块（<code>标签）样式就是不折行的

**Comment by liygheart** [comment]
一行代码如果过长，代码块下就会出现滚动条，然后往左滑，去查看隐藏的代码的时候，整个页面就会出现上下滚动的现象，然后代码库左滑的动作也停止了，，难道只有我手机是这样的？

**Comment by TakWolf** [comment]
启用兼容模式之后还会有上下滚动的问题吗？

**Comment by liygheart** [comment]
兼容模式开了之后，不会上下滚动了，但左右滑动很卡。

**Comment by TakWolf** [comment]
左滑非常卡吗？
我这里感觉还好

**Comment by TakWolf** [comment]
代码折行的问题，确定不折行。
css只能实现粗暴的折行，没法实现按照语义折行。
CNode移动页面是折行的，GitHub是不折行的。
没有觉得折行更利于阅读，因此样式跟GitHub保持一致。

**Comment by TakWolf** [comment]
WebView产生的各种问题，目前倾向于使用兼容模式处理。
除非有严重的问题，否则不打算深入处理（出现的问题基本上也没法解决，包括样式、手势、性能）。
