### ISSUE TITLE
啥时候出夜间模式啊

### ISSUE THREAD

**Issue by yuu2lee4** [TakWolf/CNode-Material-Design#4]
晚上看着刺眼

**Comment by TakWolf** [comment]
主要是因为懒，有空在搞

**Comment by alsotang** [comment]
。。。还有这需求啊，挺接地气的。。

2015-10-19 19:11 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by TakWolf** [comment]
@yuu2lee4 夜间模式已更新
