### ISSUE TITLE
markdown没有解析粗体

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#40]

**Comment by TakWolf** [comment]
是本地的还是远程的？我这里测试可以解析啊

**Comment by liygheart** [comment]
话题详情里看到的`**xxxxx**`

**Comment by liygheart** [comment]
![image](https://cloud.githubusercontent.com/assets/6915570/15604106/f656925c-2430-11e6-9e0d-ccf8e7dc4b2d.png)

图终于传上来了。。。

**Comment by TakWolf** [comment]
这个是服务端解析的，可能原因是两端没加空格的时候，跟其他字符冲突了
