### ISSUE TITLE
分享成功后没有返回之前app的弹窗

### ISSUE THREAD

**Issue by liygheart** [TakWolf/CNode-Material-Design#41]
回去补个图

**Comment by TakWolf** [comment]
分享使用的是系统接口（语义是发送 ACTION_SEND），是否弹出返回之前APP这个逻辑是目标应用自己处理的，跟客户端没关系

**Comment by liygheart** [comment]
![qq 20160530213512](https://cloud.githubusercontent.com/assets/6915570/15650892/6f4c94f2-26ae-11e6-819e-48c42ec99e35.jpg)

就是这个

**Comment by TakWolf** [comment]
@liygheart 分享使用的是系统接口，这个是目标app自己的逻辑，不由客户端处理

**Comment by liygheart** [comment]
意思是目标app要配合处理一下？

**Comment by TakWolf** [comment]
分享使用的是系统接口，语义是发送 ACTION_SEND，凡是实现了这个语义接收器的APP都会出现在列表中，但是，数据传递给目标APP之后，怎么处理是目标APP自己的逻辑，不是客户端的逻辑，也没法有客户端控制。

UC分享出现提示对话框，是因为UC用了QQ提供的分享SDK。分享SDK跟原生接口表现不一致，这个是QQ的实现问题。
