### ISSUE TITLE
关于侧滑返回

### ISSUE THREAD

**Issue by nichbar** [TakWolf/CNode-Material-Design#42]
个人觉得在查看详细文章页添加一个侧滑返回功能可以提高用户体验，这样用起来更顺手。
可参考[Slidr](https://github.com/r0adkll/Slidr)

**Comment by tomoya92** [comment]
我也觉得方便
记得去年我邮件反馈过一次 ，@TakWolf  说安卓上的返回按键已经很方便了，就没做！

**Comment by TakWolf** [comment]
@nichbar @tomoya92 

滑动返回这个是可以做的，我没做
因为要添加一个 `<item name="android:windowIsTranslucent">true</item> `，这个会对一些正在用的动画产生影响。

侧滑返回本身出现是为了解决iOS大屏化之后手持操作的问题。
Android本身是有物理返回键的，感觉滑动返回不是特别必要，就没加。

**Comment by TakWolf** [comment]
我目前更倾向于不加这个特性。

但是如果你们觉得这个十分需要，是可以添加的。

**Comment by tomoya92** [comment]
我把 https://github.com/ikew0ng/SwipeBackLayout 这个库加到CNodeMD里编译了一下，在手机上体验了一下，感觉没啥影响

你说的要加 `<item name="android:windowIsTranslucent">true</item>` 这个也加了，好像是在打开话题的是个会闪一下白色，之后就没啥问题了

不知道大大说的 `正在用的动画产生影响` 是哪地方？

**Comment by TakWolf** [comment]
@tomoya92 

Android 5.0 开始，支持一种新的动画，叫做 Transition Animation，就是CNodeMD中点击用户头像进入详情页面的内个动画。
支持这个动画，style-v21要添加如下配置   
```
<item name="android:windowContentTransitions">true</item>
```
因为底层实现上也是基于背景透明的，所以你添加了这个配置，
```
<item name="android:windowIsTranslucent">true</item>
```
动画是有问题的，你可以自己测试一下

当然，这并非是一个大问题

**Comment by tomoya92** [comment]
好像是有个问题，不过，为了返回，忍了 😂
