### ISSUE TITLE
也在列表发现了重复数据

### ISSUE THREAD

**Issue by tomoya92** [TakWolf/CNode-Material-Design#44]
之前在osc的安卓客户端上发现列表有重复的时候，发了个动态，结果被osc客户端相关人员语气很不好说用的是老版本，我把版本号发他了，他不说话了，着实心里不爽，osc的员工素质也就那样！

下面说正题，在cnode社区客户端也发现这问了

![screenshot_20160701-080421](https://cloud.githubusercontent.com/assets/6915570/16508265/f145e5bc-3f63-11e6-882d-b2f85d4263b4.png)

**Comment by TakWolf** [comment]
CNode的话题有上浮特性，无论何种分页结构，都无法保证有序性。

出现这个情况，是你在加载历史数据的时候，话题出现了上浮的行为，顺序被打乱

**Comment by tomoya92** [comment]
虽然不太懂 ，也就是说cnodejs服务端反的数据就是有问题的是吧？

**Comment by TakWolf** [comment]
不能说数据是有问题的，而是  以最后回复时间排序 -> 这种排序本身就不是稳定的排序结构
在这种排序条件下，无法实现列表顺序的稳定性

**Comment by tomoya92** [comment]
哦哦，明白了，也就是说刷新了第一页后，下面有回复，被顶上去了，结果应该出现在第二页的，被挤上去了，然后第一页最后一条就出现在了第二页的第一条，也就出现了重复

原来如此，thx
