### ISSUE TITLE
cnode有没有的iOS客户端？

### ISSUE THREAD

**Issue by jieyou** [TakWolf/CNode-Material-Design#45]
rt

**Comment by TakWolf** [comment]
iOS商店上架的有两个客户端，直接在appstore搜索cnode关键字就能看到了

其他的你在这里找找看吧 https://github.com/cnodejs-client

**Comment by jieyou** [comment]
谢谢

**Comment by alsotang** [comment]
https://github.com/cnodejs-client 这个地址屌。。

2016-07-06 17:12 GMT+08:00 Jieyou Qin [佑界] <notifications@github.com>:
