### ISSUE TITLE
nexus5x扫描二维码摄像头反了

### ISSUE THREAD

**Issue by tomoya92** [TakWolf/CNode-Material-Design#46]
![image](https://cloud.githubusercontent.com/assets/6915570/17476788/6b3c2b9e-5d94-11e6-90cf-6ead9a1de0b8.png)

**Comment by TakWolf** [comment]
系统版本是多少

**Comment by tomoya92** [comment]
现在是android7

**Comment by TakWolf** [comment]
第三方相机方向正常吗？

**Comment by tomoya92** [comment]
没装第三方的相机软件，我记得这好像是nexus5x的一个硬件bug

**Comment by TakWolf** [comment]
手里没有nexus5x实体设备，模拟器的nexus5x镜像没发现问题，可以的话希望可以测试一下第三方相机是不是正常的。

总之这个bug反馈给第三方库作者了

**Comment by tomoya92** [comment]
poco相机，打开app，拍照就是反的，相机360拍照倒是正常的，但在CNodeMD里，扫描二维码调用的一直都是系统相机

**Comment by TakWolf** [comment]
@tomoya92 关注一下，最新的rom这个问题还存在吗？

**Comment by tomoya92** [comment]
还是有这个问题

**Comment by tomoya92** [comment]
确实是因为硬件的问题 http://mobile.163.com/15/1111/11/B84T79UJ0011179O.html

**Comment by TakWolf** [comment]
我靠，这么坑

**Comment by tomoya92** [comment]
我今天把这个项目里扫码部分代码拿出来放到我的项目里，扫码是好的，跟你项目里唯一不同的是我用的版本比较新，是 `compile 'com.dlazaro66.qrcodereaderview:qrcodereaderview:2.0.2‘`  你用的还是1.0.0 

我在想会不会是人家更新了这个bug呢？你更新一下试试看

**Comment by TakWolf** [comment]
fix at https://github.com/TakWolf/CNode-Material-Design/commit/2776ffa8f1d46c3ac217372e49ea659bb4de0535
