### ISSUE TITLE
Crypto 这个类解密出错

### ISSUE THREAD

**Issue by zhangle1** [TakWolf/CNode-Material-Design#49]
在方法   public byte[] decrypt(@NonNull SecretKey secret, @NonNull IvParameterSpec iv, @NonNull byte[] data)

cipher.init(Cipher.DECRYPT_MODE, secret);    少了一个iv参数 ， 
在手机nexus 5s 上面报错切换夜间模式的时候报错。   

不知道是不是我的问题=。=

**Comment by TakWolf** [comment]
异常栈可以粘贴一下吗？
