### ISSUE TITLE
沉浸式。。。。

### ISSUE THREAD

**Issue by yuu2lee4** [TakWolf/CNode-Material-Design#5]
我又来提建议了 `(*∩_∩*)′

**Comment by TakWolf** [comment]
。。。你要求真多

**Comment by alsotang** [comment]
好吧。。今天第一次听说沉浸式。。。

**Comment by TakWolf** [comment]
@alsotang 

沉浸式状态栏 ，就是UI延伸到系统状态栏

IOS很早就是了，Android从4.4才开始支持

**Comment by TakWolf** [comment]
更新1.0.12
兼容Android 4.4.X的沉浸式状态栏已实现

但是由于APP本身主题就是偏黑色的，所有除了主界面的抽屉菜单，其他的都不明显

**Comment by yuu2lee4** [comment]
good  马上给你报个bug
