### ISSUE TITLE
gradle build 失败

### ISSUE THREAD

**Issue by dymdebug** [TakWolf/CNode-Material-Design#52]
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest
gradle build 编译到这一步，出现了
java.lang.NullPointerException (no error message)
然后build 失败了，这个是什么原因呢？

我无论用1.2还是最新develop都是碰到这个问题。

**Comment by TakWolf** [comment]
https://github.com/TakWolf/CNode-Material-Design/blob/develop/app/build.gradle#L25

这里需要配置友盟key,请随便给一个非空字符串。

是不是这个原因？

**Comment by dymdebug** [comment]
每个版本都编译通过了，就是这个问题。
谢谢提供帮助！
