### ISSUE TITLE
强烈建议进入小米应用商店

### ISSUE THREAD

**Issue by XGHeaven** [TakWolf/CNode-Material-Design#6]
我在小米应用商店中没有找到相关的APP，强烈建议上架！！！

**Comment by TakWolf** [comment]
其实主要是因为比较懒，小米开发者的审核一直没弄。。。
近期会上架小米商店的

**Comment by XGHeaven** [comment]
@TakWolf 好的么~~~期待中哦~

**Comment by TakWolf** [comment]
@XGHeaven 小米商店已上架

http://app.mi.com/detail/118728

**Comment by alsotang** [comment]
审核那么快？

2015-11-09 19:01 GMT+08:00 TakWolf <notifications@github.com>:
