### ISSUE TITLE
如何自行打成apk包？ 在哪里修改参数连接到自己的服务器？

### ISSUE THREAD

**Issue by fandasoft** [TakWolf/CNode-Material-Design#68]
1. 能否概要列举一下打成apk包的步骤？
2. 在哪里修改服务器连接参数。

谢谢！

**Comment by tomoya92** [comment]
@fandasoft 把 `build.gradle` 里的 `String umengAppKey = System.getenv('CNODEMD_UMENG_APP_KEY')` 改成 `String umengAppKey = ""` 就可以了，可以打一个没签名的包，想打个有签名的包，可以自己用as创建一个自己的签名证书，然后用它打包就可以了

[这个issue](https://github.com/TakWolf/CNode-Material-Design/issues/66)里说会移除友盟统计，不知道为啥还没有移除，我刚clone的代码还有友盟统计 @TakWolf

**Comment by TakWolf** [comment]
https://github.com/TakWolf/CNode-Material-Design/blob/1.4.0/app/src/main/java/org/cnodejs/android/md/model/api/ApiDefine.java
在这里修改服务器地址配置。

https://github.com/TakWolf/CNode-Material-Design/blob/1.4.0/app/src/main/AndroidManifest.xml#L132
在这里修改调起协议。

其他有一些零散的包括 分享文案、关于页面、尾巴文案

**Comment by fandasoft** [comment]
@TakWolf @tomoya92  谢谢两位，已经运行起来了。 
好东西，谢谢分享 👍 🙏
