### ISSUE TITLE
代码被遮挡。。。。

### ISSUE THREAD

**Issue by yuu2lee4** [TakWolf/CNode-Material-Design#7]
![Uploading cnode.png…]()
额图片传不上来 你自己看吧

另外吐槽一句  沉浸式确实太不明显了

**Comment by TakWolf** [comment]
哪块被遮挡？这里吗？

![image](https://cloud.githubusercontent.com/assets/6064962/11109633/5ee88e1e-892d-11e5-9b69-0d93adf1c27a.png)

CSS样式中代码是不折行的。

**Comment by yuu2lee4** [comment]
好吧 我发现可以左右滑动  但是在我这里没有横向滑动条

**Comment by TakWolf** [comment]
这个问题我也发现了，在我的一些测试设备上（Lenovo系列），也是没滚动条的，估计和WebView有关系

目前还没找到解决方案

![image](https://cloud.githubusercontent.com/assets/6064962/11109741/c90d047c-892e-11e5-80b3-df1759c45ee0.png)


设备是 Lenovo A320t

**Comment by yuu2lee4** [comment]
你这个是用什么框架开发的、、

**Comment by TakWolf** [comment]
原生的

Markdown渲染用的是WebView

**Comment by TakWolf** [comment]
问题迁移到 https://github.com/TakWolf/CNode-Material-Design/issues/26
