### ISSUE TITLE
安卓版的登录，为什么不能直接输入用户名与密码登录？

### ISSUE THREAD

**Issue by fandasoft** [TakWolf/CNode-Material-Design#70]
如题。
毕竟，如果要应用到一个非技术的群，不管是github，还是扫码，大家都会搞糊涂。
所以想知道如果要实现用户名、密码这种传统的登录方式，如何进行？
此外，如果采用“通过微信、QQ登录”，具体如何实现？ 望指点！

**Comment by tomoya92** [comment]
@fandasoft 网站都不支持用户名密码登录，你让app里怎么实现？

**Comment by fandasoft** [comment]
@tomoya92  有意思😄。 确实，现在的App链接的事CNodejs.org地址， 我没有意识到。 
现在我部署的服务器，是可以通过用户名／密码登录的，故有此问，如果要增加上用户名／密码登录的话，有什么建议么？ 🙏

**Comment by TakWolf** [comment]
@fandasoft   CNode线上从来没开放过用户名登录，所以客户端现在没有这个部分。
正常客户端只有扫码登录一种方式。GitHub登录是我通过 hack 方式实现的。

**Comment by TakWolf** [comment]
如果想要客户端支持用户名登录，非常好改，但是需要了解一点相关知识：
1. 服务端需要扩展一个登录api
2. 客户端调整一下登录页面和调用
