### ISSUE TITLE
不知道怎么去运行项目

### ISSUE THREAD

**Issue by qzqs** [TakWolf/CNode-Material-Design#71]
你好，总是报错误
Error:(4, 0) Gradle DSL method not found: 'google()'
Possible causes:<ul><li>The project 'CNode-Material-Design-develop' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 2.3.3 and sync project</a></li><li>The project 'CNode-Material-Design-develop' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>
-----------------------------------------------
然后我把'google()删除增加url 'https://maven.google.com'
然后又报错
Error:(17, 0) Gradle DSL method not found: 'url()'
Possible causes:<ul><li>The project 'CNode-Material-Design-develop' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 2.3.3 and sync project</a></li><li>The project 'CNode-Material-Design-develop' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>
请问作者我该怎么去运行？

**Comment by TakWolf** [comment]
develop 分支最新节点需要 Android Studio 3.x，你需要升级IDE

或者 保持 Android Studio 2.x，使用 tag 1.4.0 的代码
https://github.com/TakWolf/CNode-Material-Design/tree/1.4.0

**Comment by TakWolf** [comment]
你的Android 低于 2.3.3 吗？
点一下内个  Upgrade plugin to version 2.3.3 and sync project 试一下

**Comment by qzqs** [comment]
你好，我使用的是2.33.已经点击了Upgrade plugin to version，还是一样报错误，然后我修改成
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io'
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}
然后出现了版本冲突~
Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources]
想请问下，我2.33版本只能使用以前1.40代码了么？除非我升级我的gradle？

**Comment by TakWolf** [comment]
1.4.0 是目前线上的版本，环境是 2.3.3

develop 分支升级到 3.0。Gradle 除了 google 依赖之后，部分还使用了新写法，必须升级 Android Studio。并且 support 2.6 有很多 bug，需要等官方修复。

**Comment by qzqs** [comment]
那我现在先学习1.40版本，等我升级了我的gradle成3.X再学习作者的最新版本。

**Comment by qzqs** [comment]
2.33 分支最新节点也运行成功了，上面修改，版本冲突的原因是因为却上了友盟分享的key，按照提示修改就运行成功了
