### ISSUE TITLE
评论会无故增长

### ISSUE THREAD

**Issue by XGHeaven** [TakWolf/CNode-Material-Design#8]
![image](https://cloud.githubusercontent.com/assets/9291212/11166661/11f6a4fc-8b7a-11e5-9311-de383ab6d0fc.png)
经常在滚动的时候，原本是好的，滚动多了，然后原本有的评论就会变长了。。。

**Comment by TakWolf** [comment]
WebView的一个bug，下一个版本解决这个问题

我比较在意截图左上角的绿线是怎么出来的

**Comment by XGHeaven** [comment]
因为那是小米3的电量显示

**Comment by alsotang** [comment]
哈哈。这绿线不偏不倚，刚好在中间，我也以为是个什么东西呢

2015-11-15 12:46 GMT+08:00 Xu Tianyang <notifications@github.com>:

**Comment by XGHeaven** [comment]
@alsotang 哈哈，因为我个人有点强迫症，所以看到不是100%的电量不舒服，于是我就改成了这样 :joy:

**Comment by TakWolf** [comment]
@XGHeaven

这个问题不太好解决，Webview问题太多了...

有一个方案，一开始就加载所有item，不进行重用，这样就不会涉及高度计算的问题。但是有很大风险会oom

打算尝试用webview渲染一个完整的列表试一下

**Comment by XGHeaven** [comment]
我不太懂安卓，大体意思就是每次滚动加载并重现显示的时候会重新渲染webview，而此时就会发生高度计算的错误？
能否尝试换一个webview框架进行尝试？

**Comment by TakWolf** [comment]
@XGHeaven 差不多是这个意思

客户端没有办法直接渲染Markdown。

话题页面，顶部的帖子内容，底下回复的Item，每一个的内容部分都是一个独立的WebView控件。也就是说，这个页面其实有10多个WebView。列表在滑动的时候，控件是在回收池不断重用的。有一些系统版本的WebView的高度计算是有问题的（目前测试是在 4.x 和 2.x的某些手机上有这个问题），一旦撑开了就回不去了。所以滚动几下，高度就变成最大的内个了。

目前 话题页面 和 通知列表 页面有这个问题


现在有这么几个解决方案：

1. 回复不支持富文本显示，用普通的TextView控件显示，通知列表也是用普通文本显示。没有了WebView也就没了这个问题。（最不想采用的方案）

2.一次性加载并渲染所有的item，不使用回收池加载。这样WebView高度是一口气计算好的，没有控件重用也就没这个问题。性能是最差的，占用内存最高。一个帖子如果有50多个回复，其实就是一口气加载了50的WebView。因为这个是原生控件，这个量很容易发生oom，感觉特别危险。

3.列表渲染的部分使用纯粹的前端来做，放到一个WebView，不使用原生的部分。
这个方案是我目前可能打算使用的，然后设置页面提供一个选择，使用原生渲染或者使用WebView渲染

**Comment by XGHeaven** [comment]
我也比较赞成使用第三种方案，但是我觉得一旦用了前端页面，和手机的交互又是另一个问题了。以及如何和手机内部的设计风格保持一致。
还有就是segemengfault的markdown感觉没有问题，不知道他们是怎么做到的。

**Comment by TakWolf** [comment]
问题迁移到 https://github.com/TakWolf/CNode-Material-Design/issues/26
