### ISSUE TITLE
可以加个密码登陆吗，我尝试过自己弄，源码复杂，弄不了

### ISSUE THREAD

**Issue by zhidd** [TakWolf/CNode-Material-Design#84]
可以加个密码登陆吗，我尝试过自己弄，源码复杂，弄不了

**Comment by TakWolf** [comment]
这个客户端全部功能都是定向与 CNode 的，需要 CNode 开启密码登录功能，客户端才会适配该功能。

----------------------------

自己添加密码登录并不复杂，你要保证：

1.你自己部署的后端需要有密码登录接口

2.改造 token 验证接口调用为密码登录接口
https://github.com/TakWolf/CNode-Material-Design/blob/1.4.0/app/src/main/java/org/cnodejs/android/md/model/api/ApiService.java#L102

3.变更登录页面表单为密码登录
https://github.com/TakWolf/CNode-Material-Design/blob/develop/app/src/main/java/org/cnodejs/android/md/ui/activity/LoginActivity.java

**Comment by tomoya92** [comment]
也可以在app里开一个网页，然后登录后到设置页面拿token再回到app里进行保存，这样会比较简单
