### ISSUE TITLE
报这个错误Cause: null value in entry: UMENG_APPKEY=null

### ISSUE THREAD

**Issue by tianshaokai** [TakWolf/CNode-Material-Design#9]

**Comment by TakWolf** [comment]
项目默认集成友盟统计和自动更新组件。

1.
在 http://www.umeng.com/ 创建应用，并将AppKey配置到项目中，具体做法是：
在项目根目录下找到 local.properties 文件，在结尾添加一行

    umeng.appkey=[你申请的AppKey]

2.
你也可以不申请，随便写个值也行，只要有这个字段，Gradle编译就可以通过，只是友盟组件不会起作用，但是并不影响运行

3
或者移除友盟组件，具体做法：

删除项目中的 umeng-update-sdk 整个目录
删除app/build.gradle中的如下部分：

    // 读取local.properties文件
    def Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())
    ......
     manifestPlaceholders = [
                UMENG_CHANNEL: "CNodeJS",
                UMENG_APPKEY: properties.getProperty("umeng.appkey")
        ]
    ......
    compile 'com.umeng.analytics:analytics:5.6.1'
    ......

删除app\src\main\AndroidManifest.xml中的

    ......
        
        <meta-data
            android:name="UMENG_APPKEY"
            android:value="${UMENG_APPKEY}" />

        <meta-data
            android:name="UMENG_CHANNEL"
            android:value="${UMENG_CHANNEL}" />

        
        <service
            android:name="com.umeng.update.net.DownloadingService"
            android:process=":DownloadingService" />

        <activity
            android:name="com.umeng.update.UpdateDialogActivity"
            android:theme="@style/AppDialog"
            android:screenOrientation="portrait"
            android:configChanges="orientation|keyboardHidden|screenSize" />
    .......

删除 app\src\main\java\org\cnodejs\android\md\ui\base\BaseActivity.java 中的

    @Override
    protected void onResume() {
        super.onResume();
        MobclickAgent.onResume(this);
    }

    @Override
    protected void onPause() {
        super.onPause();
        MobclickAgent.onPause(this);
    }

删除 app\src\main\java\org\cnodejs\android\md\ui\activity\MainActivity.java

     // 友盟更新
        UmengUpdateAgent.update(this);

最后整理上述文件中的package，移除没用的导入编译即可



如果你只想运行一下项目看看，推荐第二种方式
